# Generated by Django 4.0.6 on 2022-07-26 06:54

import User.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(blank=True, help_text='Email validity', null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='add',
            field=models.CharField(help_text='Enter your Address', max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postalcode',
            field=models.CharField(blank=True, help_text='Enter your postalcode', max_length=10, null=True, verbose_name='postalcode'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ManyToManyField(blank=True, help_text='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='your email', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=User.utils.create_otp_code, help_text='code', max_length=11, unique=True, verbose_name='code')),
                ('exp_time', models.DateTimeField(default=User.utils.create_end_time, help_text='Time out', verbose_name='exp_time')),
                ('type', models.IntegerField(choices=[(1, 'AUTHENTICATE'), (2, 'FORGETPASSWORD')], help_text='type', verbose_name='type')),
                ('user', models.ForeignKey(help_text='user', on_delete=django.db.models.deletion.PROTECT, related_name='otp_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
