# Generated by Django 4.0.6 on 2022-08-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_is_email_verified_alter_address_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Specifies the code used or not', verbose_name='is_used'),
        ),
    ]
