# Generated by Django 4.0.6 on 2022-08-14 14:07

import User.valid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_is_email_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ManyToManyField(blank=True, help_text='your address', to='User.address', verbose_name='address'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=User.valid.PhoneField(blank=True, help_text='your phonenumber', max_length=16, null=True, verbose_name='phonenumber'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='/home/mahsa/AlsaProject/Alsa_Project/static/assets/images/user_profile.jpg', help_text='upload your image', null=True, upload_to='profile_images', verbose_name='image'),
        ),
    ]
