# Generated by Django 4.0.6 on 2022-08-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_address_options_alter_otp_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='/home/mahsa/AlsaProject/Alsa_Project/media/profile_images/user_profile.jpg', help_text='upload your image', null=True, upload_to='profile_images/', verbose_name='image'),
        ),
    ]
