# Generated by Django 4.0.6 on 2022-08-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(blank=True, default='/profile_images/user_profile.jpg', help_text='upload your image', null=True, upload_to='profile_images/', verbose_name='image'),
        ),
    ]
