# Generated by Django 4.0.6 on 2022-08-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='postalcode',
        ),
    ]
