# Generated by Django 4.0.6 on 2022-07-17 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0002_category_category_p_details_pro_id_and_more'),
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(help_text='سبد خرید', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CartItemtoCartMe', to='Cart.cartme'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(help_text='کالاها', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CartItemtoProduct', to='Products.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartme',
            name='product',
            field=models.ManyToManyField(help_text='کالاها', through='Cart.CartItem', to='Products.product'),
        ),
        migrations.AddField(
            model_name='cartme',
            name='user',
            field=models.ForeignKey(blank=True, help_text='نام کاربری', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CartmetoCustomer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='history',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='مشتری', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HistorytoCustomer', to=settings.AUTH_USER_MODEL),
        ),
    ]
