# Generated by Django 4.0.6 on 2022-07-26 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0003_alter_category_category_p_alter_category_title_and_more'),
        ('Cart', '0002_cartitem_cart_cartitem_product_cartitem_salesman_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartme',
            name='priceTotla',
        ),
        migrations.AddField(
            model_name='cartme',
            name='priceTotal',
            field=models.PositiveIntegerField(blank=True, help_text='price total', null=True, verbose_name='priceTotal'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(help_text='cart', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CartItemtoCartMe', to='Cart.cartme'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(help_text='products', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CartItemtoProduct', to='Products.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='salesman',
            field=models.ForeignKey(blank=True, help_text='salesman', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartme',
            name='date',
            field=models.DateTimeField(auto_now=True, help_text='date'),
        ),
        migrations.AlterField(
            model_name='cartme',
            name='discount',
            field=models.CharField(help_text='discount', max_length=10, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='cartme',
            name='factor',
            field=models.JSONField(blank=True, help_text='Purchase Invoice', null=True, verbose_name='factor'),
        ),
        migrations.AlterField(
            model_name='cartme',
            name='ispaid',
            field=models.BooleanField(default=False, help_text='ispaid'),
        ),
        migrations.AlterField(
            model_name='cartme',
            name='product',
            field=models.ManyToManyField(help_text='products', through='Cart.CartItem', to='Products.product'),
        ),
        migrations.AlterField(
            model_name='cartme',
            name='user',
            field=models.ForeignKey(blank=True, help_text='user name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CartmetoCustomer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='history',
            name='cartme',
            field=models.ManyToManyField(help_text='products', to='Cart.cartme'),
        ),
        migrations.AlterField(
            model_name='history',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HistorytoCustomer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='date'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_update',
            field=models.DateTimeField(auto_now=True, help_text='date update'),
        ),
    ]
