# Generated by Django 4.0.6 on 2022-07-26 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0003_alter_category_category_p_alter_category_title_and_more'),
        ('Comment', '0002_commentme_product_commentme_user_rate_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentme',
            name='comment',
            field=models.CharField(blank=True, help_text='Enter your comment', max_length=255, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='commentme',
            name='product',
            field=models.ForeignKey(help_text='product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commenttoproduct', to='Products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='commentme',
            name='user',
            field=models.ForeignKey(blank=True, help_text='user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commenttouser', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Enter your score', max_length=1, null=True, verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(blank=True, help_text='user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratetocustomer', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
