# Generated by Django 4.0.5 on 2022-07-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='لطفا نوع محصول مورد نظر را انتخاب کنید', max_length=100, unique=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='رنگ محصول را انتخاب کنید', max_length=100, unique=True, verbose_name='color')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام محصول را وارد کنید', max_length=100, unique=True, verbose_name='product name')),
                ('image', models.ImageField(blank=True, help_text='تصویر خود را آپلود کنید ', null=True, upload_to='Products', verbose_name='image')),
                ('image1', models.ImageField(blank=True, help_text='تصویر خود را آپلود کنید ', null=True, upload_to='Products', verbose_name='image')),
                ('image2', models.ImageField(blank=True, help_text='تصویر خود را آپلود کنید ', null=True, upload_to='Products', verbose_name='image')),
                ('price', models.PositiveIntegerField(help_text='قیمت محصول را وارد کنید', verbose_name='price')),
                ('capacity', models.PositiveIntegerField(help_text='موجودی', verbose_name='capacity')),
                ('discription', models.TextField(blank=True, help_text='توضیحات مربوطه', null=True, verbose_name='discription')),
                ('brand', models.CharField(max_length=16, null=True)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('data_update', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='date and time')),
                ('product', models.ManyToManyField(to='Products.product')),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlists',
            },
        ),
    ]
