# Generated by Django 4.0.6 on 2022-07-17 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catproductmodel', to='Products.category', verbose_name='title'),
        ),
        migrations.AddField(
            model_name='details',
            name='pro_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailstoproperty', to='Products.property'),
        ),
        migrations.AddField(
            model_name='details',
            name='product_id',
            field=models.ManyToManyField(to='Products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producttocat', to='Products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='Products.color'),
        ),
        migrations.AddField(
            model_name='property',
            name='cat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propertytocat', to='Products.category'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlisttocustomer', to=settings.AUTH_USER_MODEL),
        ),
    ]
