# Generated by Django 4.0.6 on 2022-07-26 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0002_category_category_p_details_pro_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_p',
            field=models.ForeignKey(blank=True, help_text='Please select the desired product type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catproductmodel', to='Products.category', verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Please select your product name.', max_length=100, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(help_text='Choose the color of your product', max_length=100, unique=True, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='details',
            name='detail',
            field=models.CharField(blank=True, help_text='product', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='pro_id',
            field=models.ForeignKey(help_text='property', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailstoproperty', to='Products.property'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(help_text='Enter your product brand', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='capacity',
            field=models.PositiveIntegerField(help_text='product inventory', verbose_name='capacity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(help_text='category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producttocat', to='Products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(help_text='Choose the color of your product', to='Products.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_update',
            field=models.DateTimeField(auto_now=True, help_text='date update'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, help_text='date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.TextField(blank=True, help_text='Relevant descriptions', null=True, verbose_name='discription'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='upload your image', null=True, upload_to='Products', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, help_text='upload your image', null=True, upload_to='Products', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, help_text='upload your image', null=True, upload_to='Products', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Please select your product name.', max_length=100, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='Enter the product price', verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='cat_id',
            field=models.ForeignKey(blank=True, help_text='category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propertytocat', to='Products.category'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(blank=True, help_text='property name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='datetime',
            field=models.DateTimeField(auto_now=True, help_text='data and time', verbose_name='date and time'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(help_text='product', to='Products.product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(blank=True, help_text='user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlisttocustomer', to=settings.AUTH_USER_MODEL),
        ),
    ]
