# Generated by Django 4.1 on 2022-08-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_color_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(help_text='Choose the color of your product', max_length=100, null=True, unique=True, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, help_text='Choose the color of your product', to='Products.color'),
        ),
    ]
