# Generated by Django 4.0.5 on 2022-07-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('phone_number', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='phone_number')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Introduction/Intro')),
                ('discretion', models.TextField(verbose_name='discretion')),
            ],
            options={
                'verbose_name': 'Introduction',
                'verbose_name_plural': 'Introductions',
            },
        ),
    ]
