# Generated by Django 4.0.6 on 2022-07-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Introduction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intro',
            name='discretion',
        ),
        migrations.AddField(
            model_name='intro',
            name='discription',
            field=models.TextField(blank=True, help_text='Enter your discription', null=True, verbose_name='discretion'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='address',
            field=models.CharField(blank=True, help_text='Enter your Address', max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload your photo', null=True, upload_to='Introduction/Intro'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='phone_number',
            field=models.PositiveBigIntegerField(blank=True, help_text='Enter your phone number', null=True, verbose_name='phone_number'),
        ),
    ]
