# Generated by Django 4.0.6 on 2022-07-17 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0002_category_category_p_details_pro_id_and_more'),
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='product',
            field=models.ManyToManyField(to='Products.product'),
        ),
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='newstocustumer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notif_user',
            name='product',
            field=models.ManyToManyField(to='Products.product'),
        ),
        migrations.AddField(
            model_name='notif_user',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notiftocustomer', to=settings.AUTH_USER_MODEL),
        ),
    ]
