# Generated by Django 4.0.6 on 2022-07-26 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0003_alter_category_category_p_alter_category_title_and_more'),
        ('Notification', '0002_news_product_news_user_notif_user_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='file_news',
            field=models.FileField(blank=True, help_text='upload your file', null=True, upload_to='Notification/News', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_news',
            field=models.ImageField(blank=True, help_text='upload your image', null=True, upload_to='Notification/News', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='product',
            field=models.ManyToManyField(help_text='product', to='Products.product'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_new',
            field=models.TextField(help_text='Relevant descriptions', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='news',
            name='user',
            field=models.ForeignKey(blank=True, help_text='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='newstocustumer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notif_user',
            name='file_notif',
            field=models.FileField(blank=True, help_text='upload your file', null=True, upload_to='Notification/notif_user', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='notif_user',
            name='image_notif',
            field=models.ImageField(blank=True, help_text='upload your image', null=True, upload_to='Notification/notif_user', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='notif_user',
            name='product',
            field=models.ManyToManyField(help_text='product', to='Products.product'),
        ),
        migrations.AlterField(
            model_name='notif_user',
            name='text_notif',
            field=models.TextField(help_text='Relevant descriptions', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='notif_user',
            name='user',
            field=models.ForeignKey(blank=True, help_text='user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notiftocustomer', to=settings.AUTH_USER_MODEL),
        ),
    ]
